/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e235709;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Arrays;

class HitAndBlowTest {
    /**
     * countHitsが正しく動くことを確認するテスト
     * 3桁の数字をコピーして同じ配列を作る
     */
    @Test
    void testCorrectGuess() {
        HitAndBlow game = new HitAndBlow();
        int[] secretNumber = game.getSecretNumber();
        int[] correctGuess = Arrays.copyOf(secretNumber, secretNumber.length);

        int hits = game.countHits(correctGuess);

        assertEquals(3, hits);

    }

    
    }

